[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "expressions"
version = "0.1"
dependencies = ["matplotlib", "scipy", "numpy"]

[tool.hatch.build.targets.wheel]
packages = ["expressions"]